server:
  port: ${PORT:8086}
  shutdown: graceful

spring:
  config:
    import: classpath:ticketrush-observability.yml
  application:
    name: waiting-room-service
  threads:
    virtual:
      enabled: true

