server:
  port: ${PORT:8080}
  shutdown: graceful

spring:
  config:
    import: classpath:ticketrush-observability.yml
  application:
    name: api-gateway

ticketrush:
  routes:
    event-service: ${EVENT_SERVICE_URI:http://localhost:8081}
    booking-service: ${BOOKING_SERVICE_URI:http://localhost:8082}
    payment-service: ${PAYMENT_SERVICE_URI:http://localhost:8083}
    ticket-service: ${TICKET_SERVICE_URI:http://localhost:8084}
    waiting-room-service: ${WAITING_ROOM_SERVICE_URI:http://localhost:8086}

