server:
  port: ${PORT:8083}
  shutdown: graceful

spring:
  application:
    name: payment-service
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
