#!/usr/bin/env bash
# Creates .env with random local credentials, so no password or key is ever committed (NFR-SEC-03).
# docker compose reads .env automatically, and services started from an IDE import it as well.
#   ./scripts/init-dev-env.sh                      # gateway on port 8080
#   GATEWAY_PORT=18080 ./scripts/init-dev-env.sh   # if 8080 is taken
set -euo pipefail
cd "$(dirname "$0")/.."

if [ -f .env ]; then
  echo ".env already exists; delete it and the postgres volume (docker compose down -v) to start over"
  exit 0
fi

secret() { openssl rand -hex "$1"; }
umask 077
cat > .env <<ENV
# Generated by scripts/init-dev-env.sh for local development only. Not committed.
POSTGRES_PASSWORD=$(secret 24)
EVENT_DB_PASSWORD=$(secret 24)
BOOKING_DB_PASSWORD=$(secret 24)
PAYMENT_DB_PASSWORD=$(secret 24)
TICKET_DB_PASSWORD=$(secret 24)
NOTIFY_DB_PASSWORD=$(secret 24)
TICKET_SIGNING_KEY=$(secret 32)
GATEWAY_PORT=${GATEWAY_PORT:-8080}
ENV
echo "Wrote .env with fresh random credentials"
