#!/usr/bin/env bash
# Creates or completes .env with random local credentials, so no password or key is ever committed
# (NFR-SEC-03). Existing values are kept: changing a database password after the Postgres volume was
# created would lock the services out. docker compose reads .env; services started from an IDE too.
#   ./scripts/init-dev-env.sh                      # gateway on port 8080
#   GATEWAY_PORT=18080 ./scripts/init-dev-env.sh   # if 8080 is taken
set -euo pipefail
cd "$(dirname "$0")/.."

umask 077
[ -f .env ] || echo "# Generated by scripts/init-dev-env.sh for local development only. Not committed." > .env

added=()
secret() { openssl rand -hex "$1"; }
add() { # name value: appended only when .env does not define it yet
  if ! grep -q "^$1=" .env; then
    echo "$1=$2" >> .env
    added+=("$1")
  fi
}

add POSTGRES_PASSWORD "$(secret 24)"
add EVENT_DB_PASSWORD "$(secret 24)"
add BOOKING_DB_PASSWORD "$(secret 24)"
add PAYMENT_DB_PASSWORD "$(secret 24)"
add TICKET_DB_PASSWORD "$(secret 24)"
add NOTIFY_DB_PASSWORD "$(secret 24)"
add TICKET_SIGNING_KEY "$(secret 32)"
add ADMISSION_TOKEN_KEY "$(secret 32)"
add GATEWAY_PORT "${GATEWAY_PORT:-8080}"

if [ ${#added[@]} -eq 0 ]; then
  echo ".env is complete; nothing changed"
else
  echo "Added to .env: ${added[*]}"
fi
