#!/usr/bin/env bash
# Creates or completes .env with random local credentials, so no password or key is ever committed
# (NFR-SEC-03). Existing values are kept: changing a database password after the Postgres volume was
# created would lock the services out. docker compose reads .env; services started from an IDE too.
#   ./scripts/init-dev-env.sh                      # gateway on port 8080
#   GATEWAY_PORT=18080 ./scripts/init-dev-env.sh   # if 8080 is taken
set -euo pipefail
cd "$(dirname "$0")/.."

umask 077
[ -f .env ] || echo "# Generated by scripts/init-dev-env.sh for local development only. Not committed." > .env

added=()
secret() { openssl rand -hex "$1"; }
add() { # name value: appended only when .env does not define it yet
  if ! grep -q "^$1=" .env; then
    echo "$1=$2" >> .env
    added+=("$1")
  fi
}

add POSTGRES_PASSWORD "$(secret 24)"
add EVENT_DB_PASSWORD "$(secret 24)"
add BOOKING_DB_PASSWORD "$(secret 24)"
add PAYMENT_DB_PASSWORD "$(secret 24)"
add TICKET_DB_PASSWORD "$(secret 24)"
add NOTIFY_DB_PASSWORD "$(secret 24)"
add REDIS_PASSWORD "$(secret 24)"
add TICKET_SIGNING_KEY "$(secret 32)"
add ADMISSION_TOKEN_KEY "$(secret 32)"
add PAYMENT_WEBHOOK_SECRET "$(secret 32)"
add KEYCLOAK_ADMIN_PASSWORD "$(secret 16)"
add GRAFANA_ADMIN_PASSWORD "$(secret 16)"
# Kafka accounts (SASL/PLAIN): the admin that sets up topics and ACLs, one per service, Kafka UI.
add KAFKA_ADMIN_PASSWORD "$(secret 24)"
add KAFKA_EVENT_SERVICE_PASSWORD "$(secret 24)"
add KAFKA_BOOKING_SERVICE_PASSWORD "$(secret 24)"
add KAFKA_PAYMENT_SERVICE_PASSWORD "$(secret 24)"
add KAFKA_TICKET_SERVICE_PASSWORD "$(secret 24)"
add KAFKA_NOTIFICATION_SERVICE_PASSWORD "$(secret 24)"
add KAFKA_UI_PASSWORD "$(secret 24)"
# Kafka UI's own login page (user admin).
add KAFKA_UI_LOGIN_PASSWORD "$(secret 16)"
# A service started from the IDE signs in to Kafka on localhost:9094 like the containers do.
add KAFKA_SECURITY_PROTOCOL SASL_PLAINTEXT
# Password of the demo accounts (organizer@, admin@, alice@, bob@, chi@, dung@ticketrush.dev).
add DEMO_USER_PASSWORD "$(secret 8)"
# Signs the tokens k6 mints; only trusted when load-test/compose.yml is layered on (see load-test/README).
add LOAD_TEST_JWT_SECRET "$(secret 32)"
add GATEWAY_PORT "${GATEWAY_PORT:-8080}"

if [ ${#added[@]} -eq 0 ]; then
  echo ".env is complete; nothing changed"
else
  echo "Added to .env: ${added[*]}"
fi
