server:
  port: ${PORT:8084}
  shutdown: graceful

spring:
  application:
    name: ticket-service
  threads:
    virtual:
      enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true
